platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Import Flutter helper methods (needed for plugins)
require File.expand_path(File.join('Flutter', 'podhelper'), __dir__)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

